//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZBlocker.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZBlocker.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;version&quot;: 9, 
        ///&quot;client_version&quot;: &quot;1.0.24.104.g92a22684&quot;, 
        ///&quot;playing&quot;: true, 
        ///&quot;shuffle&quot;: true, 
        ///&quot;repeat&quot;: false, 
        ///&quot;play_enabled&quot;: true, 
        ///&quot;prev_enabled&quot;: false, 
        ///&quot;next_enabled&quot;: false, 
        ///&quot;track&quot;: {
        ///  &quot;length&quot;: 30, 
        ///  &quot;track_type&quot;: &quot;ad&quot;
        ///}, 
        ///&quot;context&quot;: {
        ///}, 
        ///&quot;playing_position&quot;: 11.679001, 
        ///&quot;server_time&quot;: 1457449883, 
        ///&quot;volume&quot;: 0.62999922, 
        ///&quot;online&quot;: true, 
        ///&quot;open_graph_state&quot;: {
        ///  &quot;private_session&quot;: false, 
        ///  &quot;posting_disabled&quot;: true
        ///}, 
        ///&quot;running&quot;: true
        ///}.
        /// </summary>
        internal static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: 9,
        ///  &quot;client_version&quot;: &quot;1.0.24.104.g92a22684&quot;,
        ///  &quot;playing&quot;: true,
        ///  &quot;shuffle&quot;: true,
        ///  &quot;repeat&quot;: false,
        ///  &quot;play_enabled&quot;: true,
        ///  &quot;prev_enabled&quot;: true,
        ///  &quot;next_enabled&quot;: true,
        ///  &quot;track&quot;: {
        ///    &quot;track_resource&quot;: {
        ///      &quot;name&quot;: &quot;This World&quot;,
        ///      &quot;uri&quot;: &quot;spotify:track:5Fzsgjt24v7nDJdhIOIBS2&quot;,
        ///      &quot;location&quot;: {
        ///        &quot;og&quot;: &quot;https://open.spotify.com/track/5Fzsgjt24v7nDJdhIOIBS2&quot;
        ///      }
        ///    },
        ///    &quot;artist_resource&quot;: {
        ///      &quot;name&quot;: &quot;Selah Sue&quot;,
        ///      &quot;uri&quot;: &quot;spotify:artis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
    }
}
